### ISSUE TITLE
 add menu button instead of displaying commands

### ISSUE THREAD

**Issue by sanjanacheerla** [CSC510-G35-Fall2022/SmartSpend2#6]

**Comment by Culcheese** [comment]
Could you clarify what this means?

**Comment by sanjanacheerla** [comment]
check the message I tagged you in, on our discord channel

**Comment by Culcheese** [comment]
ok got it, thanks. Finished adding the menu commands now

**Comment by sanjanacheerla** [comment]
sounds good, closing this issue
